NostalgiaApp/Models/ErrorViewModel.cs
using System;

namespace NostalgiaApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NostalgiaApp/Models/ExistingNostalgiasViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NostalgiaApp.Models
{
    public class ExistingNostalgiasViewModel
    {
        public List<NostalgiaViewModel> Nostalgias = new List<NostalgiaViewModel>();
    }
}

NostalgiaApp/Models/Nostalgia.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace NostalgiaApp.Models
{
    
    public class Nostalgia
    {
        public Nostalgia(int id, string title, string description, DateTime createDate, DateTime nextReminderDate, byte[] image)
        {
            Id = id;
            Title = title;
            Description = description;
            CreateDate = createDate;
            NextReminderDate = nextReminderDate;
            Image = image;
        }

        public Nostalgia()
        {

        }

        public int Id { get; set; }
        
        [Required]
        public string Title { get; set; }
        
        [Required]
        public string Description { get; set; }

        [Required]
        [DefaultValue(true)]
        public bool IsActive { get; set; }

        [Required]
        public DateTime CreateDate { get; set; }
        
        [AllowNull]
        public DateTime NextReminderDate { get; set; }
        public byte[] Image { get; set; }
    }
}

NostalgiaApp/Models/NostalgiaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;

namespace NostalgiaApp.Models
{
    public class NostalgiaViewModel
    {
        public NostalgiaViewModel(int id, string title, string description, DateTime createDate, DateTime nextReminderDate)
        {
            Id = id;
            Title = title;
            Description = description;
            CreateDate = createDate;
            NextReminderDate = nextReminderDate;            
        }

        public NostalgiaViewModel()
        {

        }

        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Description { get; set; }

        [Required]
        [DefaultValue(true)]
        public bool IsActive { get; set; }

        [Required]
        public DateTime CreateDate { get; set; }

        [AllowNull]
        public DateTime NextReminderDate { get; set; }
        public string Image { get; set; }
    }
}

NostalgiaApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NostalgiaApp.Models;

namespace NostalgiaApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

       
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NostalgiaApp/Controllers/NostalgiaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NostalgiaApp.Data;
using NostalgiaApp.Models;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System;
using System.IO;

namespace NostalgiaApp.Controllers
{
    [Route("nostalgia")]
    public class NostalgiaController : Controller
    {
        private INostalgiaDao _nostalgiaDao;

        public NostalgiaController(INostalgiaDao nostalgiaDao)
        {
            _nostalgiaDao = nostalgiaDao;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Route("list")]
        public IActionResult ExistingNostalgiaReminders()
        {
            ExistingNostalgiasViewModel vm = new ExistingNostalgiasViewModel();          

            var nostalgias = _nostalgiaDao.GetNostalgias();

            foreach(var nostalgia in nostalgias)
            {
                vm.Nostalgias.Add(mapNostalgiaModel(nostalgia));                
            }           
            
            return View(vm);
        }

        [HttpGet]
        [Route("add")]
        public IActionResult AddNostalgia()
        {           
            return View();
        }

        [HttpPost]
        [Route("add")]
        public IActionResult AddNostalgiaToDb([Bind("Title,Description")] Nostalgia nostalgia, IFormFile File)
        {                      
            if (File != null)
            {
                if (File.Length > 0)
                {
                    var image = Image.Load(File.OpenReadStream());
                    image.Mutate(x => x.Resize(256, 256));
                    
                    string imageString = image.ToString();

                    using (var ms = new MemoryStream())
                    {                        
                        image.Save(ms, Image.DetectFormat(File.OpenReadStream()));
                        nostalgia.Image = ms.ToArray();
                    }
                }
            }

            _nostalgiaDao.SaveNostalgia(nostalgia);
            return RedirectToAction("ExistingNostalgiaReminders");            
        }

        private NostalgiaViewModel mapNostalgiaModel(Nostalgia nostalgia)
        {
            NostalgiaViewModel model = new NostalgiaViewModel();

            model.Id = nostalgia.Id;
            model.Title = nostalgia.Title;
            model.Description = nostalgia.Description;
            model.CreateDate = nostalgia.CreateDate;
            model.NextReminderDate = nostalgia.NextReminderDate;

            if (nostalgia.Image != null && nostalgia.Image.Length > 0)
            {
                string imageBase64Data =
                    Convert.ToBase64String(nostalgia.Image);

                model.Image = string.Format("data:image/jpg;base64,{0}", imageBase64Data);
            }

            return model;
        }
    }
}

NostalgiaApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@section AddToHead{
    <link href="@Url.Content("~/css/index.css")" rel="stylesheet" type="text/css" />
}

<div id="welcome-div">
    <h1 class="display-4">Nostalgia</h1>
    <p>- a sentimental longing or wistful affection for the past, typically for a period or place with happy personal associations.</p>
</div>

NostalgiaApp/Views/Nostalgia/AddNostalgia.cshtml
@{
    ViewData["Title"] = "Nostalgia Page";
}
@model ExistingNostalgiasViewModel

@section AddToHead{
    <link href="@Url.Content("~/css/index.css")" rel="stylesheet" type="text/css" />
}

<form action="add" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" id="title" name="title" class="form-control" placeholder="title" />
    </div>
    <div class="form-group">
        <label for="description">Description</label>
        <textarea id="description" name="description" class="form-control" rows="5" placeholder="description"></textarea>
    </div>    
    <div class="form-group">
        <label for="file-upload">Example file input</label>
        <input type="file" class="form-control-file" id="file-upload" name="file" />
    </div>
        <button type="submit" class="btn btn-primary">Submit</button>
</form>

NostalgiaApp/Views/Nostalgia/ExistingNostalgiaReminders.cshtml
@{
    ViewData["Title"] = "Nostalgia Page";
}
@model ExistingNostalgiasViewModel

@section AddToHead{
    <link href="@Url.Content("~/css/nostalgia-list.css")" rel="stylesheet" type="text/css" />
}

<div>
    <div id="navigation-btn-div">
        <a id="add-nostalgia-btn" asp-controller="Nostalgia" asp-action="AddNostalgia" class="btn btn-lg btn-primary">Create a new Nostalgia</a>
    </div>
    <div id="nostalgia-list-container">
        @if (Model.Nostalgias.Count == 0)
        {
            <p>You have no Nostalgias!</p>
        }
        else
        {
            foreach (var nostalgia in Model.Nostalgias)
            {
                <div class="nostalgia-div">
                    <h3>@nostalgia.Title</h3>
                    <p>@nostalgia.Description</p>
                    @*if (nostalgia.Image != null && nostalgia.Image.Length > 0)
                        {
                            <img src="@nostalgia.Image" />
                        }*@
                    <p>@nostalgia.NextReminderDate.Month/@nostalgia.NextReminderDate.Day/@nostalgia.NextReminderDate.Year</p>

                </div>
            }
        }
        </div>
    </div>

NostalgiaApp/Views/Nostalgia/Index.cshtml
@{
    ViewData["Title"] = "Nostalgia Page";
}
@section AddToHead{    
    <link href="@Url.Content("~/css/nostalgia-index.css")" rel="stylesheet" type="text/css" />
}

<div id="title-div">
    <h1 class="display-4">Nastolgia Landing Page</h1>    
</div>

<div id="nav-div">
    <a class="btn-nav-anchor" asp-controller="Nostalgia" asp-action="ExistingNostalgiaReminders"><div class="action-btn">View Nostalgia Reminders</div></a>
    <a class="btn-nav-anchor" asp-controller="Nostalgia" asp-action="AddNostalgia"><div class="action-btn">Add New Reminder</div></a>
</div>

NostalgiaApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NostalgiaApp</title>
    @if (IsSectionDefined("AddToHead"))
    {
        @RenderSection("AddToHead", required: false)
    }
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NostalgiaApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Nostalgia" asp-action="Index">Nostalgias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - NostalgiaApp
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>